# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='이름')),
                ('aliases', models.CharField(default='', help_text='콤마로 구분', max_length=250, verbose_name='별칭')),
            ],
            options={
                'verbose_name_plural': '여론조사기관 목록',
                'verbose_name': '여론조사기관',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='기호 번호')),
                ('name', models.CharField(db_index=True, default='', max_length=20, verbose_name='이름')),
                ('party', models.CharField(default='', max_length=20, verbose_name='소속당')),
                ('icon', models.ImageField(upload_to='', verbose_name='아이콘')),
            ],
            options={
                'verbose_name_plural': '후보자 목록',
                'verbose_name': '후보자',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('total', '종합'), ('region', '지역별'), ('age', '연령별'), ('sex', '성별')], default='total', max_length=20, verbose_name='종류')),
                ('category', models.CharField(db_index=True, default='', help_text='지역, 연령대, 성별', max_length=20, verbose_name='세부 카테고리')),
                ('percent', models.FloatField(default=0.0, verbose_name='지지율')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Candidate', verbose_name='후보')),
            ],
            options={
                'verbose_name_plural': '지지율 목록',
                'verbose_name': '지지율',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='여론조사명')),
                ('published', models.DateField(default=None, null=True, verbose_name='여론조사 발표일')),
                ('info', models.TextField(default='', verbose_name='여론조사 정보')),
                ('link', models.CharField(default='', max_length=200, verbose_name='링크')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Agency', verbose_name='여론조사기관')),
            ],
            options={
                'verbose_name_plural': '여론조사 목록',
                'verbose_name': '여론조사',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Survey', verbose_name='여론조사'),
        ),
    ]
