# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20170502_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='percent',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='기호 번호'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='소속당'),
        ),
    ]
