# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20170502_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='출마여부'),
        ),
    ]
