# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20170502_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='category',
        ),
        migrations.AddField(
            model_name='rating',
            name='target',
            field=models.CharField(db_index=True, default='', help_text='지역명, 연령대, 성별', max_length=20, verbose_name='대상'),
        ),
    ]
