# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20170502_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='unique',
            field=models.CharField(default='', help_text='문재인후보지지율,날짜,여론조사기관명의 Hash값', max_length=100, verbose_name='설문조사 고유번호'),
        ),
    ]
