# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_survey_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='unique_str',
            field=models.TextField(default='', verbose_name='테스트용'),
        ),
    ]
