# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20170504_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitDatabaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='업데이트명')),
                ('is_execute', models.BooleanField(default=False, verbose_name='실행 여부')),
                ('execute_date', models.DateTimeField(auto_now_add=True, verbose_name='실행일')),
            ],
            options={
                'verbose_name': '데이터베이스 업데이트 로그',
                'verbose_name_plural': '데이터베이스 업데이트 로그 목록',
            },
        ),
        migrations.RemoveField(
            model_name='office',
            name='aliases',
        ),
        migrations.AddField(
            model_name='office',
            name='alias',
            field=models.CharField(default='', max_length=40, verbose_name='별칭'),
        ),
    ]
