# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20170504_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='unique',
        ),
        migrations.AddField(
            model_name='survey',
            name='office',
            field=models.CharField(default='', max_length=250, verbose_name='여론조사 의뢰기관'),
        ),
    ]
