# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20170504_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='가상여부'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=80, verbose_name='여론조사명'),
        ),
    ]
