# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20170504_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='source',
            field=models.CharField(choices=[('daum', '다음'), ('naver', '네이버')], default='', max_length=10, verbose_name='출처'),
        ),
    ]
