# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_survey_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='color',
            field=models.CharField(default='#b6bcc7', max_length=7, verbose_name='색상(HEX)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.CharField(default='', max_length=250, verbose_name='사진'),
        ),
    ]
